[dependencies]

[package]
  cjc-version = "0.55.3"
  compile-option = "Pim-hXjR4w4JUc9CX9uYbWK9"
  description = ""
  link-option = ""
  name = "cjweave"
  output-type = "dynamic"
  src-dir = ""
  target-dir = ""
  version = "1.0.0"
  [package.package-configuration]
